### PR TITLE
Bug fix: Card returns to previous lane

### PR DESCRIPTION
**Pull request by alfmoh**
Fixed bugs:
1. After first successful card lane change, subsequent card lane changes don't work.
2. New card replaces existing cards

Changes:
Callback methods order updated. Action happens first before callback is called

### CODE REVIEW

**Comment by KaiSpencer** [comment]
Hi @alfmoh  
Thank you so much for this!

Currently the main branch isnt published to npm, only the v1 branch is under all 1.x.x releases.
So the changes you have made have likely fixed the yet to be released main branch (with improvements, like zustand instead of redux etc...) 

We will need to apply these changes also to the v1 branch and get that published there, and I can make a main publish for 2.x.x if you are interested in that also.
I had been holding off on publishing from main until I had more things ready, but im happy to get one published if you want to merge this and start using v2 :D

**Comment by alfmoh** [comment]
Hello @KaiSpencer , you are welcome :)

Concerning the fact that the changes need to be added to v1 too, I'm not against it but I think sooner or later, it will be best to retire v1 and focus on v2 (main) because maintaining the two versions is bound to cause issues down the road since they have quite significant changes such as state management, monorepo etc. At the end of the day, when a user downloads the package from npm, what they are primarily interested in is that, it should work and redux or zustand or any under other underlining package used doesn't really make much of a difference to most people.

The v1 can be moved to a different repo and declared as legacy so the future work will be focused on the newer version

**Comment by KaiSpencer** [comment]
Hey @alfmoh

Sure thing, my intention with the v1 branch was feature parity withthe original repository before I stared to deviate with new development. 
We can definitely merge this and make a v2 cut though.

Going forwards im wanting better test coverage, are you comfortable creating a cypress component test for this scenario? Im happy to do this onto this PR if you would prefer instead :) 

Thanks again

**Comment by alfmoh** [comment]
Hello @KaiSpencer 

You can create the test component for this scenario :)

**Pull request merged**
